version: '3.3' # specify docker-compose version

# Define the services/containers to be run
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  # https://github.com/docker-library/cassandra/issues/104#issuecomment-383211480    
  cassandra:
    image: cassandra
    ports:
    # 7000: intra-node communication
    # 7001: TLS intra-node communication
    # 7199: JMX
    # 9042: CQL
    # 9160: thrift service
    - "9042:9042"
    volumes:
    - cassandradata:/var/lib/cassandra
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    
  redis:
    image: redis
    ports:
      - "6379:6379"
      
  mongodb: 
    image: mongo 
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles #--rest
#   command: --smallfiles --rest --auth  // if there is a password set in mongo.

volumes:
  mongodata:  
#    driver: local-persist
#    driver_opts:
#      mountpoint: ./data  
  cassandradata: 
       