server:
  port: 8082

spring:
  application:
    name: post-service

logging:
  level:
    com.example: DEBUG
    org.springframework.data: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
